- src/cyw43.h
- src/cyw43_ctrl.c
- src/cyw43_ll.c
- src/cyw43_ll.h
Re-enable cyw43_read_iovar_u32 and add cyw43_get_ioctl_u32
Rename cyw43_do_ioctl_u32 to cyw43_set_ioctl_u32 as it better describes
what it's used for.
Fixes #5
Signed-off-by: Peter Harper <peter.harper@raspberrypi.com>
> src: Add a method to get power management value.

- src/cyw43_lwip.c
The lwip mDNS API has changed which can cause problems building it. The suggestion is that this code should not be in the driver anyway, so remove it.
Fixes #17
> src: Remove mDNS from cyw43-driver.

- src/cyw43.h
- src/cyw43_lwip.c
This is related to #19 should resolve #18.
Thanks to the good hint in from @peterharperuk  https://github.com/georgerobotics/cyw43-driver/issues/18#issuecomment-1225913653 I was able to use the mac address filtering. With these changes applied, ipv6 works perfectly for me.
And hints? Should I split up the 2 commits into to separate PRs?
> Implement a multicast filtering api and enable v6 for lwip

- src/cyw43_ctrl.c
* The value for WLC_SUP_KEYXCHANGE_WAIT_G1 is 10 not 11.
> cyw43_ctrl.c: Fix handshake message G1 event value.

- src/cyw43_ll.c
I've been debugging this issue for a while and I can reproduce it with 2 different access points, and with both the PYBD_SF2 and Portenta-H7 (with the closed source driver). On both boards, if the EAPOL key exchange times out (which happens very frequently with the APs I'm testing with) the boards will rejoin (using the same timeout) and just get stuck in a rejoin/timeout loop. See the following trace, which repeats forever:
```
[  293728] ASYNC(0000,ASSOC_REQ_IE,0,0,0)
[  293729] ASYNC(0000,AUTH,0,0,0)
[  293735] ASYNC(0000,ASSOC_RESP_IE,0,0,0)
[  293735] ASYNC(0000,ASSOC,0,0,0)
[  293735] ASYNC(0001,LINK,0,0,0)
[  293762] ASYNC(0000,JOIN,0,0,0)
[  293762] ASYNC(0000,SET_SSID,0,0,0)
[  294736] ASYNC(0000,PSK_SUP,4,15,0)
Supplicant M1 timeout event
[  295045] …
```
> cyw43_ll.c: Increase the default EAPOL key messages timeout.

- src/cyw43_ctrl.c
Checking the map file, `cyw43_async_event_name_table` was in RAM instead of flash, despite being "read only".
Needs an additional const.
> Make cyw43_async_event_name_table const so it goes to flash

- src/cyw43_ll.c
Fix for #27 
- Add handling for auth_type == 0 to IF.
- The IF on line 2038 provided handling for networks without security (open networks). However, this handling is never used due to it being ignored by the IF on line 2013.
- Reproducibly fixes open network connection issues observed by Raspberry Pi Pico W MicroPython users (discussed [here](https://github.com/micropython/micropython/issues/9016#issuecomment-1219896195)) using `security=0` parameter.
> Add handling for open networks to cyw43_ll_wifi_join.

- src/cyw43_ll.c
- src/cyw43_ll.h
Joining to wifi via BSSID doesn't appear to work.
Don't set the channel count if the channel is not set.
Fixes #54
> src: Channel fix in cyw43_ll_wifi_join.

- src/cyw43_config.h
- src/cyw43_ll.c
Minor changes to make this version of the driver behave identically to the version that was previously used in MicroPython for stm32 boards such as GR pybd and Arduino Portenta.
The driver worked as-is, but with two performance regressions fixed by this PR.
- The SDIO interrupt was not being handled correctly.
- The 1DX module (used on both boards) used needs to set revision 17 when using the "worldwide" region.
Also makes it return `EINVAL` rather than `-1` (i.e. `EPERM`) when setting an invalid auth type for connection.
_This work was funded through GitHub Sponsors._
> cyw43_ll: Support using this driver on stm32 (pybd, portenta).

- tests/sdio/Makefile
Dependency generation makes sure targets are determined out of date should any included headers be out of date.
Tested by rebuilding across changes to cyw43_configport.h.
> Add dependency generation to Makefile

- src/cyw43_ll.c
I saw this bug when I enabled debug messages in the new cyw43-driver by adding the following 3 lines to cyw43_configport.h:
```
#define CYW43_DEBUG(...) printf(__VA_ARGS__)
#define CYW43_VDEBUG(...) printf(__VA_ARGS__)
#define CYW43_VERBOSE_DEBUG 1
```
> src/cyw43_ll: Fix missing newline after some WARN and DEBUG messages.

- src/cyw43_sdio.c
This means the file doesn't have to be excluded from the build if CYW43_USE_SPI is defined.
> Guard cyw43_sdio implementation with #if !CYW43_USE_SPI.

- src/cyw43.h
- src/cyw43_ctrl.c
- src/cyw43_ll.c
- cyw43_ll_wifi_ap_get_stas does not perform checks on the return value of cyw43_get_ioctl. On error (e.g. timeout), invalid num_stas values can be used in the following memcpy call, leading to crashes
- cyw43_ll_wifi_ap_get_stas now returns the return code of cyw43_do_ioctl on error
- Perform bounds checks before using memcpy. This requires the  parameter num_stas to contain the size (in MAC addresses) of the supplied buffer.
- Associated functions in cyw43_ctrl.c set num_stas to 0 on error
> Fix get_stas() bug

- src/cyw43_lwip.c
Synchronises with the change to remove this macro from the main MicroPython repo in https://github.com/micropython/micropython/pull/13763.
> cyw43_lwip: Remove STATIC macro.

- src/cyw43_lwip.c
If LWIP_NETIF_HOSTNAME=0 you can't call netif_set_hostname.
Fixes #79
> src: netif_set_hostname might not exist.

- src/cyw43_ctrl.c
Without this change, it's impossible to get self->itf_state's CYW43_ITF_AP bit cleared.
> updating itf_state when AP gets shut down

- src/cyw43_ctrl.c
Resolves race condition in #106 by moving the call to `cyw43_wifi_ap_set_up` after the call to `cyw43_cb_tcpip_init` in `cyw43_wifi_set_up`. Since bringing the link up by `cyw43_wifi_ap_set_up` completes asynchronously it is now guaranteed that the setting of `NETIF_FLAG_LINK_UP` will not get clobbered by `cyw43_cb_tcpip_init` if it finishes too early.
This will also resolve https://github.com/adafruit/circuitpython/issues/8718.
> Fix race in AP interface set up.

- src/cyw43_ll.c
- tests/sdio/Makefile
Resolves #99 by using `memmove` instead of `memcpy` for operands that are coincident in memory. This pull also resolves compile errors when attempting integration of the latest `cyw43-driver` into CircuitPython 9.0.0.
> Use memmove for operands coincident in memory.

- src/cyw43.h
> fix(comments): align errors descriptions

- src/cyw43_ll.c
This patch replaces "__uint16_t" with "uint16_t" to fix a build issue
when using non-gcc toolchain. "__uint16_t" is not a standard C type
and it will fail to build when using toolchains like Clang.
> src/cyw43_ll: Replace "__uint16_t" with "uint16_t"

- src/cyw43_lwip.c
Using this macro means the code works correctly when LWIP_SINGLE_NETIF is enabled.
Fixes issue #124.
> src/cyw43_lwip: Use NETIF_FOREACH to iterate over all netif's.

- src/cyw43.h
Doing some testing with various power saving modes gives the following:
- CYW43_NO_POWERSAVE_MODE costs about 36mA in idle STA mode while connected to an AP (the cyw43xx stays on during idle).
- CYW43_PM1_POWERSAVE_MODE and CYW43_PM2_POWERSAVE_MODE cost about 2mA in idle STA mode while connected to an AP.
For all three of the pre-defined constants `CYW43_DEFAULT_PM`, `CYW43_AGGRESSIVE_PM` and `CYW43_PERFORMANCE_PM`, doing a fast `ping -i 0.1 <ip>` to the cyw43, there's pretty much no difference (they all have low latency).  That's because they all use `CYW43_PM2_POWERSAVE_MODE` and the fast ping is supplying constant traffic over the air and keeping the cyw43 awake.
Doing a standard 1-second interval ping its possible to see the difference between these three pre-defined constants: …
> src/cyw43: Improve power-save constants so their names match behaviour.

- .github/workflows/code_formatting.yml
ubuntu-latest recently changed to 24.04, which changed uncrustify, so pin it to the previous version to get the correct formatting (until the uncrustify configuration is updated).
> github/workflows: Pin code formatting to ubuntu-22.04 for uncrustify.

- src/cyw43_ctrl.c
- src/cyw43_ll.c
- src/cyw43_spi.c
- src/cyw43_spi.h
This adds support for (general) SPI as a transport backend to communicate with the cyw43xx chip.  To use this transport, a port must provide the `cyw43_spi_xxx` functions defined in `cyw43_spi.h`, and enable the configuration option `CYW43_USE_SPI`.  The interrupt pin is configured as `CYW43_PIN_WL_IRQ`.
This feature was tested on a board using a Murata 1YN connected in gSPI mode.
This PR was also tested on a Pico 2 W and PYBD-SF2 to check for any regressions.  None were found.
> src/cyw43_spi: Add support for gSPI transport.
